name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.6.5
  - numpy
  - Pillow
  - opencv-python
  - matplotlib
  - tensorflow==1.14
  - pip
  - pip:
    - matplotlib
